asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/section.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java

In order to avoid additional markup only needed by the Confluence publisher, the title meta information (`:title: Page Title`) is now optional. In case it is not defined, the page title is defined by the top-level heading (`= Page Title`). If both are defined, the title meta information is used. If neither of them is defined, an exception is thrown.
As a consequence, the page title is no longer added to the page content (as it is already displayed by Confluence above the page content).

Optional title meta information

---

README.md
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_table.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-maven-plugin-sample/doc/index.adoc
pom.xml

Supports tables with and without header and simple text content.
Required upgrade to AsciiDoctorJ 1.5.4.1.

Simple table support

---

README.md
asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-converter/src/test/resources/includes/_included-page.adoc
asciidoc-confluence-publisher-converter/src/test/resources/includes/page.adoc
asciidoc-confluence-publisher-maven-plugin-sample/doc/index.adoc
asciidoc-confluence-publisher-maven-plugin-sample/doc/index/_included-page.adoc
asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluenceConverter.java

- support for include:: directive (required adjustment of safe mode and setting of `basedir` property in asciidoctor
**to be discussed**:
- currently, asciidoc pages included into other pages need to use the `_` as prefix in the file name and are excluded from normal conversion based on this pattern (same prefix is used by `AsciiDocDirectoryWalker` of  AsciidoctorJ)

Support for include directive

---

.travis.yml
README.md
asciidoc-confluence-publisher-converter/pom.xml
asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-converter/src/test/resources/plantuml/included-diagram.puml
asciidoc-confluence-publisher-converter/src/test/resources/plantuml/page.adoc
asciidoc-confluence-publisher-maven-plugin-sample/doc/included-diagram.puml
asciidoc-confluence-publisher-maven-plugin-sample/doc/index.adoc
asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluenceConverter.java
pom.xml

* embed plantuml diagram sources directly into asciidoc pages
* include external plantuml diagram sources
*Notes*:
* this required to adjust the safe mode to `UNSECURE`in order to allow the inclusion of generated images from the output directory which is outside of the documentation root directory (otherwise, the documentation root directory gets polluted with asciidoc meta data during diagram generation)
* reading the page title had to be adjusted to avoid parsing the whole page structure, but only reading the document meta data (otherwise, asciidoc failed complaining about not being able to find generated plantuml diagram images)

added support for embedding or including plantuml diagrams

---

README.md
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_olist.html.slim
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_ulist.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-maven-plugin-sample/doc/index.adoc

- support for bullet (unordered) lists up to 5 levels
- support for numbered (ordered) lists up to 5 levels
*To Discuss*
- should asciidoc checkbox lists be supported and mapped to confluence `ac:task` element?

Bullet and numbered lists

---

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluenceConverter.java
asciidoc-confluence-publisher-maven-plugin/src/test/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluenceConverterTest.java
asciidoc-confluence-publisher-maven-plugin/src/test/resources/org/sahli/asciidoc/confluence/publisher/maven/plugin/doc/index/sub-page.adoc

* fixed converter to pass in parent directory of asciidoc file (not generated output root path) as images output directory

Fix embedded plantuml diagrams in nested pages

---

.travis.yml

- temporarily configure previous (non-trusty) build environment
- see https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch

Fix Failed Builds on Travis Trusty Build Environment

---

pom.xml

Based on discussions with the sonatype support, an upgrade to the latest nexus-staging-maven-plugin could solve the broken maven metadata XML issue (see #56)

upgrade nexus-staging-maven-plugin to version 1.6.8

---

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java
asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-deleted-attachment-space-key.json
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-existing-page-and-existing-attachment-space-key.json
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-existing-page-space-key.json
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-root-space-key-multiple-pages.json
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-root-space-key-page-with-attachments.json
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-with-space-root-ancestor-id.json
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-without-ancestor-id.json
asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java

This pull request newly defines the ancestor id as a mandatory parameter and introduces a symbolic name (SPACE_ROOT) to refer to the space id (as the space id cannot be found easily using the confluence UI).
Resolves #44

Avoid accidental removal of pages when ancestor id is missing

---

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java

The `Matcher.appendReplacement` used in the cdata post-processor by default interprets dollar and backslash signs during replacement. In order to use the replacement as a literal, `Matcher.quoteReplacement` must be used. 
Fixes #85

Fix cdata replacements with regular expression symbols

---

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactory.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/RequestFailedException.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/utils/InputStreamUtils.java
asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java
asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java
asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactoryTest.java
asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluenceConverter.java
asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocPagesStructureProvider.java
asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/FolderBasedAsciidocPagesStructureProvider.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluenceConverterTest.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/FolderBasedAsciidocPagesStructureProviderTest.java
asciidoc-confluence-publisher-converter/src/test/resources/encoding/iso-encoded-source.adoc
asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java

- new optional Maven plugin parameter `sourceEncoding` (defaults to UTF-8)
Resolves #94

Encoding configuration support

---

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_table.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index/05-tables.adoc

Update HTML table slim to support AsciiDoc cell content in table. Reference implementation: https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/html5/block_table.html.slim

Support AsciiDoc cell content in table

---

asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluencePage.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/metadata/ConfluencePublisherMetadata.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/metadata/ConfluencePublisherPublishStrategy.java
asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java
asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/http/page-content.json
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-existing-page-ancestor-id-replace.json
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-multiple-page-ancestor-id-replace.json
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-multiple-page-ancestor-id.json
asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-zero-page-space-key-replace.json
asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
asciidoc-confluence-publisher-docker/Dockerfile
asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java

In some cases you might want to keep siblings in your ancestor instead of cleaning everything up.
I made the default so that there are no breaking changes.

Implement REPLACE_ANCESTOR publish strategy

---

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/helpers.rb
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_anchor.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index/01-pages.adoc

See "Links within Pages" in documentation section
Resolves #21 and #116

Support for internal cross-references

---

asciidoc-confluence-publisher-client/src/it/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherIntegrationTest.java
asciidoc-confluence-publisher-client/src/it/resources/attachments/attachmentOne.txt
asciidoc-confluence-publisher-client/src/it/resources/attachments/attachmentTwo.txt
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java
asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java

Attachments are not added for root page when REPLACE_ANCESTOR publishing strategy is used

Attachments are not added for root page using REPLACE_ANCESTOR

---

.gitignore
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_image.html.slim
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_listing.html.slim
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_olist.html.slim
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_paragraph.html.slim
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_ulist.html.slim
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_image.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index/04-paragraphs.adoc
asciidoc-confluence-publisher-doc/etc/docs/00-index/06-images.adoc
asciidoc-confluence-publisher-doc/etc/docs/00-index/07-listings.adoc

this a pr for issue #145 .
It add title to block where the method exist.
I used h4 for most title, except h6 for image_block captioned title, which use h6.

add title or alt text to most converted block

---

asciidoc-confluence-publisher-cli/pom.xml
asciidoc-confluence-publisher-cli/src/it/java/org/sahli/asciidoc/confluence/publisher/cli/ArgumentsParserTest.java
asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/ArgumentsParser.java
asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java
asciidoc-confluence-publisher-client/src/it/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherIntegrationTest.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java
asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
asciidoc-confluence-publisher-docker/Dockerfile
asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java

The PR modify ConfluenceRestClient to accept a configuration switch in its constructor that enable/disable SSL verification "skipping".
If disabled the HTTPClient of ConfluenceRestClient is build as usual
If enabled the HTTClient is build with a empty SSLContext, i.e. a context that does not validate the proposed certificate.

#148: add option to disable ssl by providing a custom SSLContext to HttpClientBuilder

---

asciidoc-confluence-publisher-maven-plugin/pom.xml
pom.xml

Looks like it is not used nor in the publisher neither transitively by other dependencies.

Remove guava from dependencies

---

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/section.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index/01-pages.adoc

Resolves #165 (for internal cross references with same Confluence page only).
Note: applying this PR will add anchors to all section titles (independent whether custom anchors or ids are defined) and thus, will lead to re-publication of all existing pages after upgrade.

Support for internal cross references to sections

---

asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java

Fixes #171 
(Automated tests are part of branch https://github.com/confluence-publisher/confluence-publisher/tree/feature/integration-tests-for-docker-based-publishing, but are currently blocked due to issues with resolving Docker host address from "inside" on CircleCI)

Fix for publishing strategy with Docker image-based publishing 

---

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/_toc.html.slim
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_toc.html.slim
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/embedded.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
asciidoc-confluence-publisher-doc/etc/docs/00-index/12-table-of-contents.adoc

- ToC based on "toc" Confluence macro
- default (top of page) and macro mode (within page content)
- support for custom levels
Closes #87

Table of Contents

---

asciidoc-confluence-publisher-cli/src/it/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClientIntegrationTest.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/RequestFailedException.java
asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java
asciidoc-confluence-publisher-docker/src/it/java/org/sahli/asciidoc/confluence/publisher/docker/DockerBasedPublishingIntegrationTest.java
asciidoc-confluence-publisher-maven-plugin/src/it/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojoIntegrationTest.java
asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java

Streamlines and improves logging in case of error while publishing, either due to non-200 responses from Confluence, or due to connection issues.
In addition, full stack traces are now logged when debug log level is enabled in Maven (using `-X`)
Resolves #223

Improved error logging

---

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_listing.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index/07-listings.adoc

Adds support for enabling line numbers for source blocks using `linenums` (per source block)  or `:source-linenums-option:` (per page), and for specifying a custom line number start index using the `start` block attribute.
Resolves #215

Line numbers for source blocks

---

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index/07-listings.adoc

As Confluence is not able to properly display the source highlighting information for AsciiDoc source highlighters, source highlighters should have no effect when publishing to Confluence, instead relying on the internal source highlighting mechanism of Confluence.
Resolves #216

Neutralize potentially existing source highlighter

---

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java

Fallback to no-op listener in both ConfluencePublisher constructors.

---

asciidoc-confluence-publisher-cli/src/it/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClientIntegrationTest.java
asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java
asciidoc-confluence-publisher-client/pom.xml
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceClient.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java
asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
asciidoc-confluence-publisher-docker/publish.sh
asciidoc-confluence-publisher-docker/src/it/java/org/sahli/asciidoc/confluence/publisher/docker/DockerBasedPublishingIntegrationTest.java
asciidoc-confluence-publisher-maven-plugin/src/it/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojoIntegrationTest.java
asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java

Currently the Confluence Publisher assumes that Confluence is
configured to accept unlimited HTTP requests. Unfortunately there are
two complications:
Confluence Data Center allows administrators to limit the
number of REST api calls per second
For on-premise instances, solutions such as NGINX can be configured
to reduce stress on Confluence.
This change will extend the CLI api with the optional setting
maxRequestsPerSecond which allows you to specify the maximum
number of HTTP calls per second.
Decided to extend the constructor(s) of ConfluenceRestClient as
all previous connection related parameters are managed as such - feel
free to suggest another approach.
The RateLimiter provided by guava is commonly used for this
purpose, light weight and is provided under the same license
(Apache …

feat: add rate limiter for http requests

---

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java

Adds support for use of user-provided attributes (not only document attributes) in page title. This requires manual placeholder replacements since asciidoctor converter does not accept user attributes when reading the document header.
Resolved #265

Support for user attributes in page titles

---

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluenceConverter.java
asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java

Fixes #283 by working around a confluence issue that prevents pages being updated if they have been converted to the new confluence editor.
https://jira.atlassian.com/browse/CONFCLOUD-69902
Implemented by extending the `replaceCrossReferenceTargets` post processor as it seems to be impossible to pass variables into the Slim templates.

Add confluence space key to links by page title

---

asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java
asciidoc-confluence-publisher-client/src/it/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherIntegrationTest.java
asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java
asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java

Use `enableHttpClientSystemProperties` to enable support for configuring the underlying HTTP client using system properties and use the corresponding system properties documented on https://hc.apache.org/httpcomponents-client-4.5.x/current/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html
Fixes #302

Support configuring underlying HTTP client using system properties

---

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java
asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc

Possible implementation of issue #317.
Changes:
* Renamed the `password` variable in the rest client to `passwordOrPersonalAccessToken` to denote its dual use
(as also indicated by existing documentation)
* Added the ability to use `Bearer` authentication in addition to `Basic` authentication
* Added test case
* Adjusted documentation
As this is my first PR here, any comments to improve are welcome.

Issue 317: Allow use of a Personal Access token for on-premise servers

---

asciidoc-confluence-publisher-converter/pom.xml
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
asciidoc-confluence-publisher-doc/etc/docs/00-index/10-plantuml.adoc
pom.xml

The following changes were made to support C4-PlantUML:
- Updated AsciidoctorJ to 2.5.1 from 2.4.0
- Updated AsciidoctorJ-Diagram to 2.1.2 from 2.0.2
- Updated PlantUML to 1.2021.2 from 1.2019.6
- Added a C4-PlantUML diagram to file 10-plantuml.adoc
- Updated two test cases to use the image dimensions generated by the updated version of PlantUML.
Resolves #310

Added support for C4-PlantUML diagrams.

---

asciidoc-confluence-publisher-maven-plugin/pom.xml
pom.xml

Issue #352 
Updated the "plexus-sec-dispatcher" dependency (not been maintained since May 2011) for the asciidoc-confluence-publisher-maven-plugin to avoid vulnerabilities

Updated the plexus-sec-dispatcher dependency

---

asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java

This is for Issue #370 
Confluence-publisher already supports using an access token with specifying an empty password. 
This just did not work for the maven plugin, as the XML DOM will not set username to an empty string when specifying \<username>\</username> but will set username to null. 
This PR removes the requirement for the username to be non-null as the implementation of the token handling already treats an empty username and a null username identically.
With this change users can now just leave out the username in the maven pom.xml and specify a token in the password.
I also reworded the documentation to try to make things clear.

Allow for empty username (unset) in Maven plugin

---

pom.xml

Both most relevant asciidoctorj dependencies are not up to date.
This PR upgrades the following dependencies
- Upgrade to asciidoctorj 2.5.7
- Upgrade to asciidoctorj-diagram 2.2.3

Upgrade asciidoctorj Dependencies

---

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java

Fixes #396.
I chose to fail on warnings already instead of errors because failing early is good. However, this is of course very subjective and I am open to change this to fail on errors. Maybe we can even make this configurable with a maven property. e.g:
```xml
<configuration>
<failOn>WARN/ERROR</failOn>
</configuration>
```
I may need some help for this, though.

If Asciidocj logs warnings, fail the Maven build

---

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/helpers.rb
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_anchor.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-converter/src/test/resources/inter-document-cross-references/source-page-reference-with-anchor.adoc
asciidoc-confluence-publisher-converter/src/test/resources/inter-document-cross-references/target-page-with-anchor.adoc
asciidoc-confluence-publisher-doc/etc/docs/00-index/01-pages.adoc

This MR fixes #270 
Cross references with or without anchors are now rendered correctly and anchors are correctly navigated.
Tested cross-page references using different formats and all work correct with the changes:
<<page.adoc#,reference>> 
<<page.adoc#_anchor,reference>> 
xref:page.adoc[reference]
xref:page.adoc#_anchor[reference]
Internal Cross references on same page also keep working:
<<_anchor,reference>>
Tested with some quite complex page tree with references we used internally (Tested on Confluence 7.16.5).

#270 Fix cross page links with anchors are rendered incorrectly 

---

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_image.html.slim
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_image.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index/06-images.adoc

Our documentation standards require our Confluence images to have borders around them. There is not currently a way to do this, but adding it to the processer is not complex.
This adds support for a `border=true` attribute to the image macro which emits an `ac:border="true` attribute on the resulting `ac:image` tag.

Allow images on borders

---

asciidoc-confluence-publisher-cli/src/it/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClientIntegrationTest.java
asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java
asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
asciidoc-confluence-publisher-docker/publish.sh

This allows the Confluence XHTML to be inspected, especilly as part of a Merge Request/Pull Request workflow before being pushed into a Confluence Server.

Add the ability to retain build pages after the command exits

---

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-converter/src/test/resources/inter-document-cross-references/include-page-with-title-in-include.adoc
asciidoc-confluence-publisher-converter/src/test/resources/inter-document-cross-references/source-page-with-title-in-include-in-subdir.adoc
asciidoc-confluence-publisher-converter/src/test/resources/inter-document-cross-references/source-page-with-title-in-include.adoc
asciidoc-confluence-publisher-converter/src/test/resources/inter-document-cross-references/subdir/target-page-with-title-in-include-relative-to-this-file.adoc
asciidoc-confluence-publisher-converter/src/test/resources/inter-document-cross-references/target-page-with-title-in-include.adoc

When cross-referencing another file whose title is declared in an included file, this exception occurs: `java.lang.RuntimeException: top-level heading or title meta information must be set`
Instead of parsing just the title, the whole document is parsed
Fixes #444

Fixes #444 - Toplevel Title is not acknowledged when included

---

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_paragraph.html.slim
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/helpers.rb
asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/section.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index/03-sections.adoc
asciidoc-confluence-publisher-doc/etc/docs/00-index/04-paragraphs.adoc

Need support feature [.text-<allign>] for section in confluence
Resolves #456

[FIX] allow [.text-<allign>] in headers(section)

---

asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
asciidoc-confluence-publisher-doc/etc/docs/00-index/14-extensions.adoc
asciidoc-confluence-publisher-docker/pom.xml
asciidoc-confluence-publisher-docker/publish.sh

Allow providing new extension (read custom macros) in the /opt/extensions folder inside the container. This allows extensions to be compiled and then mounted into the publisher.
This also changes the 'asciidoc-confluence-publisher-docker' jar from being a runnable jar, to regular jar. This change was made so there's only one place that has to be updated (in the docker modeule) if the main class name ever changes.
Closes: #460

Allow exteding the classpath of the docker image

---

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_image.html.slim
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java

It seems that Confluence Cloud defaults to rendering images as block (rather than inline) now. Wrapping the image in a `<span>` tag seems to cause the import API to work correctly and render inline images as inline.
Fixes #472

Wrap inline images in a `span` tag to force inline rendering

---

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluenceConverter.java
asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocPagesStructureProvider.java
asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/FolderBasedAsciidocPagesStructureProvider.java
asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
asciidoc-confluence-publisher-doc/etc/docs/00-index/13-additional-features.adoc

Exposes the following custom attributes:
- `cp-source-path`: relative file path from base directory
- `cp-source-file`: filename with extension
- `cp-source-name`: filename without extension
Resolves #248

Provide access to source file information
