.gitignore, .travis.yml, asciidoc-confluence-publisher-client/pom.xml, asciidoc-confluence-publisher-client/src/it/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherIntegrationTest.java, asciidoc-confluence-publisher-client/src/it/resources/single-page/single-page.xhtml, performConfluenceSmokeTest.sh, pom.xml, waitForConfluenceStartup.sh
- startup of confluence docker container in travis build pipeline
- simple startup wait script
- smoke test against confluence rest api
=> End-to-end Testing Pipeline

README.md, asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/helpers.rb, asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_anchor.html.slim, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-maven-plugin-sample/doc/index.adoc
- detection of external links based on simple pattern taken from helper method from asciidoctor helper script
=> External Links

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/NotFoundException.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/RequestFailedException.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java
=> improve error logging

asciidoc-confluence-publisher-client/src/it/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherIntegrationTest.java, asciidoc-confluence-publisher-client/src/it/resources/single-page/invalid-xhtml.xhtml, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java
=> Fix error on missing content-hash property value when updating a page

asciidoc-confluence-publisher-client/pom.xml, asciidoc-confluence-publisher-converter/pom.xml, asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, pom.xml
* solved via unescaping of escaped html in cdata blocks with help of post-processor
Resolves #36
=> Fix broken html escaping in listings

.travis.yml, asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
- via lifecycle phase binding
- via command line
Resolves #45
=> Document maven execution

.travis.yml
do not import pgp key if pull request is from fork (secret variables are not exposed by github due to security restrictions)
=> Fix pull request builds from forks

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
=> set encoding explicitly for source files to UTF-8

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
=> XHTML as backend for the documentation

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java
=> Fix authentication for confluence root url with context path

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluenceConverter.java, asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java, asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/NoOpPageTitlePostProcessor.java, asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/PageTitlePostProcessor.java, asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/PrefixAndSuffixPageTitlePostProcessor.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluenceConverterTest.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/NoOpPageTitlePostProcessorTest.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/PrefixAndSuffixPageTitlePostProcessorTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java
- based on page title post processor accepted by converter / page
Resolves #12
=> Page prefix and suffix

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherListener.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java, asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/metadata-zero-page-space-key.json, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java
=> Introduction of a publisher listener for page changes (add, change, delete)

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_image.html.slim, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index/06-images.adoc
=> Support for inline images

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_admonition.html.slim, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index/08-admonitions.adoc
=> Support for tip macro

asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-doc/etc/docs/00-index/01-pages.adoc, asciidoc-confluence-publisher-doc/etc/docs/00-index/02-includes.adoc, asciidoc-confluence-publisher-doc/etc/docs/00-index/_included-content.adoc
=> Resource resolving documentation

CONTRIBUTING.md, README.adoc, asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
=> Contribution guidelines

.travis.yml
=> Configure documentation publishing

asciidoc-confluence-publisher-doc/etc/docs/00-index/05-tables.adoc
enhances table documentation after merging support for AsciiDoc-enhanced table cells
=> Align tables documentation

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/RequestFailedException.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java
=> Enrich API call failure handling with request content (when available)

asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceClient.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactory.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/payloads/Version.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactoryTest.java, asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/http/add-page-request-ancestor-id.json, asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/http/add-page-request-without-version-message.json, asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-docker/Dockerfile, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java
=> Integration of PR #124 (Add parameter to publish comment into Page History section)

asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java
Resolves #131, implemented by @Aloren in PR #129
=> Integration of PR #129 (Add ability to skip plugin execution)

asciidoc-confluence-publisher-client/src/it/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherIntegrationTest.java, asciidoc-confluence-publisher-client/src/it/resources/attachments/attachmentOne.txt, asciidoc-confluence-publisher-client/src/it/resources/attachments/attachmentTwo.txt, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java
Resolves #133, implemented by @Aloren in PR #134
=> Integration of PR #134 (Attachments are not added for root page using REPLACE_ANCESTOR)

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_listing.html.slim, asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/helpers.rb, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
Do not use lang tag for not supported one by confluence code language
=> listing: Do not use lang tag for not supported one by confluence

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_listing.html.slim, asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/helpers.rb, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index/07-listings.adoc
Resolves #138, implemented by @Aloren in PR #137
=> Integration of PR #137 (listing: Do not use lang tag for not supported one by confluence)

pom.xml
Fixes security issues reported by GitHub security alerts.
=> Upgrade jackson-databind dependency due to security issues

asciidoc-confluence-publisher-cli/pom.xml, asciidoc-confluence-publisher-cli/src/it/java/org/sahli/asciidoc/confluence/publisher/cli/ArgumentsParserTest.java, asciidoc-confluence-publisher-cli/src/it/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClientIntegrationTest.java, asciidoc-confluence-publisher-cli/src/it/resources/index.adoc, asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/ArgumentsParser.java, asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java, asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluenceConverter.java, asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluenceConverterTest.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-converter/src/test/resources/org/sahli/asciidoc/confluence/publisher/converter/doc/index.adoc, asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-docker/Dockerfile, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java
reworked pr of @laurentverbruggen and added tests (https://github.com/confluence-publisher/confluence-publisher/issues/54)
=> Add support for AsciiDoc user defined attributes

asciidoc-confluence-publisher-cli/pom.xml, asciidoc-confluence-publisher-cli/src/it/java/org/sahli/asciidoc/confluence/publisher/cli/ArgumentsParserTest.java, asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/ArgumentsParser.java, asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java, asciidoc-confluence-publisher-client/src/it/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherIntegrationTest.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java, asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-docker/Dockerfile, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java
Resolves #148, implemented by @gleroi in PR #150
=> Integration of PR #150 (add option to disable ssl by providing a custom SSLContext to HttpClientBuilder)

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java
We are using Confluence 6.11.2
Can you pls review and comment?
=> #153 added CookieSpecs to RequestConfig for defaultHttpClient

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_image.html.slim, asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_image.html.slim, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index/06-images.adoc
=> Support external images

asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-docker/Dockerfile, asciidoc-confluence-publisher-docker/publish.sh
Resolves #170, implemented by @mvitz in PR #169
=> Integration of PR #169 (make asciidocRootFolder configurable in docker image)

asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, pom.xml
Closes #181  (without upgrading to AsciidoctorJ 2.x)
=> Upgrade to latest AsciidoctorJ versions on 1.5.x release

asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
=> Documentation for Confluence Cloud

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactory.java, pom.xml
=> Upgraded httpcomponent dependencies to v4.5.10.

asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherListener.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java
Logs whenever an attachment gets added, updated or deleted (similar to logs written when adding, updating or deleting pages)
Resolves #221
=> Enhanced log for attachment publishing

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/PublishingStrategy.java, asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
Resolves #196.
This PR is to gather feedback.
Suggestion: Don't merge yet, I would like to do some more testing first.
=> Publishing strategy: Append to ancestor, keep children

asciidoc-confluence-publisher-docker/src/it/java/org/sahli/asciidoc/confluence/publisher/docker/DockerBasedPublishingIntegrationTest.java, asciidoc-confluence-publisher-docker/src/it/resources/testcontainers.properties
=> Stabilize integration tests

asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java
Enable the ability to set command line parameters to the maven plugin
=> Enable read maven properties using the -D prefix.

asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-maven-plugin/src/it/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojoIntegrationTest.java, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java
Resolves #250, implemented by @AndreNicolauGoncalves in PR #233
=> Integration of PR #233 (Enable read maven properties using the -D prefix)

asciidoc-confluence-publisher-converter/pom.xml, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluenceConverterTest.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/GraphvizInstallationCheck.java
=> Runtime check for Graphviz/Dot executable when executing tests

asciidoc-confluence-publisher-client/src/it/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherIntegrationTest.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java
Resolves #197, implemented by @znerd in PR #202
=> Integration of PR #202 (Fallback to no-op listener in both ConfluencePublisher constructors)

asciidoc-confluence-publisher-cli/src/it/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClientIntegrationTest.java, asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java, asciidoc-confluence-publisher-client/src/it/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherIntegrationTest.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceClient.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-docker/src/it/java/org/sahli/asciidoc/confluence/publisher/docker/DockerBasedPublishingIntegrationTest.java, asciidoc-confluence-publisher-maven-plugin/src/it/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojoIntegrationTest.java, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java
Resolves #258 , implemented by @KevinDeJong-TomTom in PR #260
=> Integration of PR #260 (add rate limiter for http requests)

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
=> Path to AsciiDoc file in conversion exception

asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-maven-plugin/pom.xml, asciidoc-confluence-publisher-maven-plugin/src/it/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojoIntegrationTest.java, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java, pom.xml
Resolves #256, implemented by @jomu78 in PR #257
=> Integration of PR #257 (support username and password defined in settings.xml)

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/_toc.html.slim, asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_image.html.slim, asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/helpers.rb, asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_anchor.html.slim, asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_image.html.slim, pom.xml
=> Updated asciidoctorj to 2.4.0 and asciidoctorj-diagram to 2.0.2

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_listing.html.slim, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index/07-listings.adoc
Resolves #281, implemented by @zeldigas in PR #286
=> Integration of PR #286 (Feature/collapseable code block)

asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java, asciidoc-confluence-publisher-client/src/it/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherIntegrationTest.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceClient.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactory.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/payloads/Version.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactoryTest.java, asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/http/update-page-request-with-ancestor-id.json, asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-docker/Dockerfile, asciidoc-confluence-publisher-docker/publish.sh, asciidoc-confluence-publisher-maven-plugin/src/main/java/org/sahli/asciidoc/confluence/publisher/maven/plugin/AsciidocConfluencePublisherMojo.java, pom.xml
Resolves #277, implemented by @sergey-ushakov in PR #279
=> Integration of PR #279 (Add configuration parameter to publish changes via "Update" and …)

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactory.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactoryTest.java, asciidoc-confluence-publisher-client/src/test/resources/org/sahli/asciidoc/confluence/publisher/client/http/set-property-by-key-with-space-in-key-request-payload.json, asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index/11-attachments.adoc, asciidoc-confluence-publisher-doc/etc/docs/files/attachment with space in filename.txt
=> Support for attachments with spaces in filename

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java
=> Replace Asciidoctor deprecated API usages with the new ones

pom.xml
Fixes https://github.com/confluence-publisher/confluence-publisher/issues/336
=> Upgrade asciidoctorj-diagram to v2.2.1 to enable latest feature

asciidoc-confluence-publisher-converter/src/main/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePage.java, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-converter/src/test/resources/inter-document-cross-references/source-page-with-reference-to-target-page-with-html-character-in-title.adoc, asciidoc-confluence-publisher-converter/src/test/resources/inter-document-cross-references/target-page-with-html-character-in-title.adoc
=> Support page titles with HTML special characters

asciidoc-confluence-publisher-cli/src/it/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClientTest.java, asciidoc-confluence-publisher-cli/src/main/java/org/sahli/asciidoc/confluence/publisher/cli/AsciidocConfluencePublisherCommandLineClient.java
=> Make username optional in command line client

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_listing.html.slim, asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/helpers.rb
Implements #214. Case-sensitivity is still preserved.
=> Added mapping for highlight.js language

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisher.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceClient.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClient.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactory.java, asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/RequestFailedException.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/ConfluencePublisherTest.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/ConfluenceRestClientTest.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactoryTest.java, asciidoc-confluence-publisher-client/src/test/java/org/sahli/asciidoc/confluence/publisher/client/http/RequestFailedExceptionTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc, asciidoc-confluence-publisher-doc/etc/docs/00-index/01-pages.adoc
=> Prevent pages outside of ancestor from being removed

.circleci/config.yml, pom.xml
=> Build on JDK 11

asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
Hi,
Following the links in the documentation failed due to a broken link. This PR adds the new locations.
=> Broken link to issue CRA-1276

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_anchor.html.slim, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java
=> Add support for bibliography anchors

asciidoc-confluence-publisher-client/src/main/java/org/sahli/asciidoc/confluence/publisher/client/http/HttpRequestFactory.java
=> fix: mulitpart/form-data upload request to IANA specification

asciidoc-confluence-publisher-doc/etc/docs/00-index.adoc
There is an error in the sample pom.xml configuration.
=> typo fixed

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/inline_callout.html.slim, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index/07-listings.adoc
=> #297 fix callout rendering

asciidoc-confluence-publisher-converter/src/main/resources/org/sahli/asciidoc/confluence/publisher/converter/templates/block_table.html.slim, asciidoc-confluence-publisher-converter/src/test/java/org/sahli/asciidoc/confluence/publisher/converter/AsciidocConfluencePageTest.java, asciidoc-confluence-publisher-doc/etc/docs/00-index/05-tables.adoc
=> Support for table absolute and relative table width
